# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        swift: ["6.0.0", "6.1.0"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Swift ${{ matrix.swift }}
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
